In [2]:
# 1. Import libraries

import pandas as pd

In [3]:
# 2. Load data from 2 Excel files

df_1 = pd.read_excel('C:/Users/caberoca/Danone/DACH Data and Digital Powerhouse - Data & Analytics Team/UseCaseFiles/MCE/MCE MMM Fortimel/Project/MMM_Fortimel/input_files/OCE data 2021-04.2023_TA.xlsx')
#print(df_1)

df_2 = pd.read_excel('C:/Users/caberoca/Danone/DACH Data and Digital Powerhouse - Data & Analytics Team/UseCaseFiles/MCE/MCE MMM Fortimel/Project/MMM_Fortimel/input_files/OCE data 2021-04.2023_GroupCall.xlsx')
#print(df_2)

In [8]:
df_1.head()

,Datum/Zeit,Übergeordneter Besuch: Besuchsname,Inhaber: Vollständiger Name,Besuchsname,Ist Gruppenbesuch?,Produkt: Anzeigename,Auftrag anzeigen,Anzahl Besuch-Details,OneKey ID,Call Notes,Enddatum/-zeit,Gesamtanzahl Besuchsteilnehmer,Besprochene Themen,Eindeutige Integrations-ID,Division,Account-ID,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Date & Time,Parent Call: Call Name,Owner: Full Name,Call Name,Is Group Call?,Product: Display Name,Display Order,Number Of Call Details,OneKeyId,Call Notes,End Date & Time,Total Call Attendee Count,Issues Discussed,Unique Integration ID,Division,Account ID,verketten,Group,Jahr
1,2021-01-01 07:00:00,NaN,Example,C-01686500,True,.Faltering Growth,1,1,WDEH08803503,NaN,2021-03-01 07:15:00,NaN,NaN,NaN,Hospital Paeds,0013W00000BpA3u,C-016865000013W00000BpA3u,C-01686500,2021
2,2021-01-04 00:00:00,NaN,Ramona Busch,C-01627660,0,Produkt,1,1,WDEH05822243,NaN,2021-01-04 00:30:00,NaN,NaN,10805000091096,Hospital Paeds,0013W00000Bp86S,C-016276600013W00000Bp86S,C-01627660,2021
3,2021-01-04 00:00:00,NaN,Ramona Busch,C-01631643,0,Produkt,1,1,WDER02263349,NaN,2021-01-04 00:30:00,NaN,NaN,10805000091097,Hospital Paeds,0013W00000BqApz,C-016316430013W00000BqApz,C-01631643,2021
4,2021-01-04 07:04:00,NaN,Annett Steinbach,C-01623908,0,Ernährungsteam,1,1,WDEH08189151,NaN,2021-01-04 07:34:00,NaN,NaN,11904000089227,Hospital Adults,0013W00000Bp9dp,C-016239080013W00000Bp9dp,C-01623908,2021

In [9]:
df_2.head()

,Gebiet,Besuch: Inhabername,Division,Datum/Zeit,Group,Kunde: Eindeutige External ID,Kunde: Account-ID,Kunde: NICE Professional Title,Kunde: Hauptrolle,Kunde: Accountname,...,Kunde: Account-Datensatztyp,Kunde: Zielkunde Community,Kunde: ist AI Pädiater,Call Eqs OCE (do not use),Kunde: Institutionstyp,Kunde: Strukturtyp,Campaigns,weigthed TP,CallEQs,Verketten
0,Süd-Ost_HP_05,Ramona Busch,Hospital Paeds,2021-01-04 00:00:00,C-01627660,WDEH05822243,0013W00000Bp86S,NaN,NaN,Frauenklinik,...,Department-DE,0,0,0.6,Teilklinik,SER,NaN,1.0,0.5,C-016276600013W00000Bp86S
1,Süd-Ost_HP_05,Ramona Busch,Hospital Paeds,2021-01-04 00:00:00,C-01631643,WDER02263349,0013W00000BqApz,<<OHNE TITEL>>,Stationsarzt,Anna Lena Herold,...,MP (Medical Professional)-DE,0,0,0.6,NaN,NaN,NaN,1.0,0.5,C-016316430013W00000BqApz
2,Ost_HA_01,Annett Steinbach,Hospital Adults,2021-01-04 07:04:00,C-01623908,WDEH08189151,0013W00000Bp9dp,NaN,NaN,Fachkrankenhaus Coswig GmbH,...,Institution-DE,0,0,0.6,Fachkrankenhaus,ETA,NaN,1.0,0.5,C-016239080013W00000Bp9dp
3,Ost_HA_01,Annett Steinbach,Hospital Adults,2021-01-04 07:04:00,C-01631842,WDER02877480,0013W00000BqCG2,<<OHNE TITEL>>,z.N/A-Health Visitor Manager,Angelika Große,...,MP (Medical Professional)-DE,0,0,0.6,NaN,NaN,NaN,1.0,0.5,C-016318420013W00000BqCG2
4,Ost_HA_01,Annett Steinbach,Hospital Adults,2021-01-04 07:04:00,C-01633242,WDER02200189,0013W00000Bq4JW,<<OHNE TITEL>>,z.N/A-Health Visitor Manager,Patricia Reich,...,MP (Medical Professional)-DE,0,0,0.6,NaN,NaN,NaN,1.0,0.5,C-016332420013W00000Bq4JW

In [12]:
# Assign first row as header

## Access the first row and assign it as column names
new_column_names_df_1 = df_1.iloc[0]
df_1.columns = new_column_names_df_1

## Drop the first row
df_1 = df_1.drop(df_1.index[0])

## Reset the column index
df_1 = df_1.reset_index(drop=True)

In [23]:
# Filter by medical speciality

speciality = ('.Onkologie', '.Oncology')
df1_filtered = df_1[df_1['Product: Display Name'].isin(speciality)]

In [24]:
df1_filtered.head()

,Date & Time,Parent Call: Call Name,Owner: Full Name,Call Name,Is Group Call?,Product: Display Name,Display Order,Number Of Call Details,OneKeyId,Call Notes,End Date & Time,Total Call Attendee Count,Issues Discussed,Unique Integration ID,Division,Account ID,verketten,Group,Jahr
18308,2021-02-01 12:30:00,0,Annett Steinbach,C-01642017,True,.Oncology,1,3,WDEH08214537,0,2021-02-01 12:45:00,0,0,0,Hospital Adults,0013W00000Bp9fR,C-016420170013W00000Bp9fR,C-01642017,2021
18311,2021-02-01 12:30:00,C-01642017,Annett Steinbach,C-01642018,0,.Oncology,1,3,WDER02202148,0,2021-02-01 12:45:00,0,0,0,Hospital Adults,0013W00000Bq4WC,C-016420170013W00000Bq4WC,C-01642017,2021
18314,2021-02-01 12:30:00,0,Annett Steinbach,C-01642019,True,.Oncology,1,2,WDEH00162142,0,2021-02-01 12:45:00,0,0,0,Hospital Adults,0013W00000Boxny,C-016420190013W00000Boxny,C-01642019,2021
18316,2021-02-01 12:30:00,C-01642019,Annett Steinbach,C-01642022,0,.Oncology,1,2,WDER00066211,0,2021-02-01 12:45:00,0,0,0,Hospital Adults,0013W00000BpngI,C-016420190013W00000BpngI,C-01642019,2021
18318,2021-02-01 12:30:00,C-01642019,Annett Steinbach,C-01642020,0,.Oncology,1,2,WDER02200189,0,2021-02-01 12:45:00,0,0,0,Hospital Adults,0013W00000Bq4JW,C-016420190013W00000Bq4JW,C-01642019,2021

In [28]:
df1_filtered.columns

Index(['Date & Time', 'Parent Call: Call Name', 'Owner: Full Name',
       'Call Name', 'Is Group Call?', 'Product: Display Name', 'Display Order',
       'Number Of Call Details', 'OneKeyId', 'Call Notes', 'End Date & Time',
       'Total Call Attendee Count', 'Issues Discussed',
       'Unique Integration ID', 'Division', 'Account ID', 'verketten', 'Group',
       'Jahr'],
      dtype='object', name=0)

In [29]:
# Filter main table (df_2) by values from df1_filtered in column 'Call Name'

df = df_2[df_2['Group'].isin(df1_filtered['Call Name'])]

In [43]:
# Select relevant columns from df

df = df.loc[:,['Division', 'Datum/Zeit', 'Group', 'Adresse', 'Kanal', 'Mit Arzt gesprochen', 'weigthed TP', 'CallEQs']]
df.head()

,Division,Datum/Zeit,Group,Adresse,Kanal,Mit Arzt gesprochen,weigthed TP,CallEQs
12450,Hospital Adults,2021-02-01 12:30:00,C-01642017,"Friedrichstr. 41, DresdenDE_01067",persönlich (1-zu-1),1,1.0,1.0
12451,Hospital Adults,2021-02-01 12:30:00,C-01642017,"Friedrichstr. 41, DresdenDE_01067",persönlich (1-zu-1),1,1.0,1.0
12452,Hospital Adults,2021-02-01 12:30:00,C-01642019,"Neucoswiger Str. 21, Coswig b DresdenDE_01640",persönlich (1-zu-1),1,1.0,1.0
12453,Hospital Adults,2021-02-01 12:30:00,C-01642019,"Neucoswiger Str. 21, Coswig b DresdenDE_01640",persönlich (1-zu-1),1,1.0,1.0
12454,Hospital Adults,2021-02-01 12:30:00,C-01642019,"Neucoswiger Str. 21, Coswig b DresdenDE_01640",persönlich (1-zu-1),1,1.0,1.0

In [44]:
# Save final df

df.to_excel('oce_table.xlsx', index=False)